#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

destroy_temp_dir() {
  local APP="$1"
  local TMPDIR
  TMPDIR=$(mktemp -d)
  trap 'rm -rf "$TMP_WORK_DIR" > /dev/null' RETURN


  local IMAGE
  IMAGE=$(get_app_image_name $APP)

  dokku_col_log_info1_quiet "Running container $IMAGE with default CMD to build stuff!"

  docker run --rm -v $TMPDIR:/dist $IMAGE
  rm -rf "$DOKKU_ROOT/$APP/static-website-data"
  cp -r -L "$TMPDIR/." "$DOKKU_ROOT/$APP/static-website-data"
  chmod o+rx "$DOKKU_ROOT/$APP/static-website-data"
  [[ ls -1 "$DOKKU_ROOT/$APP/static-website-data" | wc -l = 0 ]] && { dokku_log_fail "ERROR!! No files copied. Check your Dockerfile, it should copy things into /dist." }
  
  dokku_log_verbose_quiet "Copied /dist"
}

destroy_temp_dir "$1"
